config:
  user.user-data: |
    #cloud-config
    package_upgrade: true
    packages:
      - make
    snap:
      commands:
      - [install, ruff]
    runcmd:
      - usermod -a -G ubuntu landscape
dev-lxc-exec:
  - make depends
  - git submodule update --init
