config:
  user.user-data: |
    #cloud-config
    package_upgrade: true
    packages:
      - make
      - python3-pip
    runcmd:
      - usermod -a -G ubuntu landscape
dev-lxc-exec:
  - make depends
  - git submodule update --init
  - sudo -H pip install --break-system-packages ruff==0.14.5
