config:
  user.user-data: |
    #cloud-config
    package_upgrade: true
    packages:
      - make
    runcmd:
      - usermod -a -G ubuntu landscape
dev-lxc-exec:
  - make depends
  - git submodule update --init
  - curl -LsSf https://astral.sh/ruff/0.14.5/install.sh | sh
