[tool.pytest.ini_options]
markers = [
    "integration: integration tests against external dependencies",
]

[tool.coverage.run]
omit = [
    "integration_tests/test_uaclient_integration.py"
]

[tool.ruff]
line-length = 88
exclude = ["snap-http"]

[tool.ruff.lint]
select = [
    "E",  # pycodestyle
    "F",  # pyflakes
    "I",  # isort
    "W",  # pycodestyle warnings
]

[tool.ruff.format]
line-ending = "lf"
