[tool.pytest.ini_options]
markers = [
    "integration: integration tests against external dependencies",
]

[tool.coverage.run]
omit = [
    "integration_tests/test_uaclient_integration.py"
]

[tool.ruff]
line-length = 88
target-version = ">=3.10"
exclude = ["snap-http/*"]

[tool.ruff.lint]
select = [
    "B",  # bugbear
    "C",  # mccabe
    "E",  # pycodestyle
    "F",  # pyflakes
    "I",  # isort
    "UP", # pyupgrade
    "SIM", # flake8
    "W",  # pycodestyle warnings
]

[tool.ruff.format]
line-ending = lf
